image:
  repository: 123456789.dkr.ecr.eu-west-1.amazonaws.com/openinfra/demoapp
  tag: latest
  pullPolicy: IfNotPresent
namespace: placeholder
spec:
  replicas: 1
  terminationGracePeriodSeconds: 0
resources:
  requests:
    cpu: "200m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "100Mi"
env:
  DB_PORT: "5432"

service:
  name: demoapp
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000
