---
name: OIDC Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  oidc:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Attempt to access another OIDC role
        uses: hashicorp/vault-action@v2.7.4
        id: import-secrets
        continue-on-error: true
        with:
          url: https://security.calvineotieno.com
          method: jwt
          role: gh-role-main
          path: auth/jwt            # FIXED
          exportEnv: false

      - name: Vault Login via GitHub OIDC
        id: vault
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: https://security.calvineotieno.com
          method: jwt
          role: gh-role-main
          path: auth/jwt

      - name: Lookup Token Issued by Vault
        id: lookup
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: https://security.calvineotieno.com
          method: token
          token: ${{ steps.vault.outputs.token }}
          path: auth/token/lookup   # FIXED: token lookup path

      - name: Export secrets to JSON
        run: |
          echo '${{ toJson(steps.import-secrets.outputs) }}' > secrets.json
          cat secrets.json
